alliedmodders/ambuild

ambuild2/frontend/prep.py
A wise man once said that VS 2010 is for tossers.
=> Change default --vs-version for --gen=vs to VS 2013

ambuild2/util.py
When using a precompiled header, `gcc -H` will output a line starting with '!' for the PCH:
```
g++ -O0 -H -c main.c
! precompiled.h.gch
main.c
. normal.h
.. x.h
Multiple include guards may be useful for:
normal.h
x.h
```
Also, in the circumstance where the PCH is incompatible with the source file (e.g. due to compiling with different options), `gcc -H` will output a line starting with 'x' for the PCH:
```
g++ -O1 -H -c main.c
x precompiled.h.gch
. precompiled.h
.. y.h
. normal.h
.. x.h
Multiple include guards may be useful for:
normal.h
precompiled.h
x.h
y.h
```
Without this patch, AMBuild fails to realize that the '.h.gch' file is a dependency of the source file, so it won't set up the proper dependency relationships to ensure that the dependent source files are rebuilt when the '.h' …
=> Handle `gcc -H` PCH prefixes properly in ParseGCCDeps

ambuild/osutil.py
On (non-english?) Windows systems attempting to decode certain output 'utf-8' as the default will fail. This change fixes those issues.
=> Fix a quirk with encodings on Windows

ambuild2/builder.py, ambuild2/damage.py, ambuild2/database.py, ambuild2/frontend/v2_0/amb2/gen.py, ambuild2/frontend/v2_1/amb2/gen.py, ambuild2/frontend/v2_1/base/context.py, ambuild2/nodetypes.py, tests/always_dirty/AMBuildScript, tests/always_dirty/configure.py, tests/always_dirty/generate.py
Right now AMBuild does not support prebuild steps - something that runs before every build, no matter what. Arbitrary steps are sort of contrary to our design, since we don't want to mess with the output folder outside of AMBuild's graph structure.
However we can introduce the concept of a command that is "always dirty". Like normal commands, these would still have outputs and still be well-ordered with respect to their dependent commands. However they would be guaranteed to run on every build, and their dirty bit would never be removed. 
This patch introduces an `ALWAYS_DIRTY` nonce on `Context` objects, which can be passed to the `input` parameter of `AddCommand`. Always-dirty commands will not necessarily run as the first step on every build, but they will *always* run. Like normal …
=> Add an ALWAYS_RUN bit to support prebuild steps.

ambuild2/frontend/v2_1/amb2/gen.py, ambuild2/frontend/v2_1/cpp/builders.py
This PR adds a few new features.
One is "Custom C++ Tools", which have just been added to the documentation [1]. The intent of this feature is to add HLSL support to AMBuild.
The other feature is that source files can now be outputs in addition to inputs. That means C++ files can now be exported from a previous build step and then directly used in a BinaryBuilder, without requiring wrapper files that `#include` it.
[1] https://wiki.alliedmods.net/AMBuild_API#Custom_C.2B.2B_Tools
=> Add the ability to specify custom CXX tools.

ambuild2/frontend/v2_0/cpp/builders.py
macOS seemed to require this, the native `ar` crashed 😨
`llvm-ar` is included as part of the Emscripten tooling and exists to combine bitcode.
=> Use llvm-ar for combining LLVM bitcode when using Emscripten

ambuild2/frontend/v2_1/cpp/detect.py
When using the 2.1 API, the cxx.version for Apple's clang ends up becoming apple-clang-clang-\<major\>.\<minor\>. So clang is repeated in the name twice. This was not the case with the 2.0 API.
=> Fix apple-clang vendor prefix in 2.1 API.

ambuild2/frontend/v2_1/cpp/builders.py
As discussed on the IRC, this will allow the build folder to have a name different from the binary name.
=> Allow localFolder attribute on BinaryBuilder/BuilderProxy to be mutable

ambuild2/frontend/v2_1/cpp/builders.py
Changes to localFolder aren't seen after _Project.Configure_ is called because the BuilderProxy constructor is called again in _finish_.
=> Propagate changes to localFolder after Project.Configure has been called

ambuild2/frontend/v2_1/amb2/gen.py, ambuild2/frontend/v2_1/cpp/compiler.py, ambuild2/frontend/v2_1/cpp/detect.py
The --symbol-files option doesn't work when using the 2.1 API. There is no chance of setting symbol_files to "separate" because the compiler object has no access to the current context's options.
=> Fix --symbol-files option in 2.1 API.

ambuild2/frontend/v2_1/cpp/detect.py, ambuild2/frontend/v2_1/cpp/gcc.py
This is implemented to be compatible for user-code with the 2.0 frontend, if scrapping that it could be a vendor for Clang instead. The other quirk here is that the version reported is the Clang version rather than the Emscripten version, I can't think of much use for the Emscripten version and it makes version tests for flags a lot simpler to write (it would be nice for AMBuild to have something to help manage that in the future though).
The 2nd commit here makes ambuild able to be used without the `emconfigure` wrapper, which is just a bit simpler to use (and makes auto-reconfigure work correctly) - it'd be nice if it could be less strict about when it is used (passing a full path to `emcc` doesn't work currently for instance), but I think it would be more annoying than useful to …
=> Emscripten support for 2.1 frontend

ambuild/cpp.py
Before:
cl /MT /W3 /nologo /Zi /Ox /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /DNDEBUG /DWIN32 /D_WINDOWS /DSOURCEMOD_BUILD /DSM_GENERATED_BUILD /I ..\includes /EHsc /TP /I ..\..\breakpad\src\src /showIncludes /c C:\projects\accelerator\test\test.cpp /Fotest_test.obj
Job failed: 'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
File "C:\python27\lib\site-packages\ambuild\job.py", line 21, in run
self.task.run(self.master, self.job)
File "C:\python27\lib\site-packages\ambuild\cpp.py", line 310, in run
self.stderr = osutil.DecodeConsoleText(sys.stderr, err)
File "C:\python27\lib\site-packages\ambuild\osutil.py", line 52, in DecodeConsoleText
return text.decode('utf8', 'replace')
AttributeError: 'NoneType' object has no …
=> [AMB1] Fix MSVC error output

ambuild2/util.py
If you run AMBuild on Windows using Python 3, text is not being colored. It works fine with Python 2, however.
This is because IO buffering is handled differently between Python 2 and Python 3. In Python 2, stdout is unbuffered by default (in a tty) because that's how the CRT handles it. Python 3 does its own buffering which appears to be line buffered by default.
This is discussed in this Python bug report: https://bugs.python.org/issue11633
So because it's line buffered, only the last call per line to `SetConsoleTextAttribute` has any effect which is often just the default text color (ConsoleNormal).
=> Fix colored text on Windows when using Python 3.x.

ambuild2/frontend/v2_0/cpp/builders.py, ambuild2/frontend/v2_1/cpp/msvc.py
Microsoft skipped vc130 and went straight to vc140 with 2015, and from
2017 started using minor version numbers which we weren't handling.
=> Fix MSVC shared PDB name on VS2015+

README.md, ambuild2/util.py, setup.py
This detects older AMBuild installs that may have been installed with
distutils, and forces their removal.
=> Prevent conflicting AMBuild installations.

ambuild2/task.py
Looked into why my build in sourcepawn failed it is due to still importing the ipc module in task.py so just put up this to fix.
=> Fix import of deleted ipc module in task.py

ambuild2/damage.py, ambuild2/database.py, ambuild2/frontend/msvc_utils.py, ambuild2/frontend/v2_1/amb2/gen.py, ambuild2/frontend/v2_1/base/context.py, ambuild2/frontend/v2_1/base/gen.py, ambuild2/frontend/v2_1/cpp/builders.py, ambuild2/frontend/v2_1/cpp/compiler.py, ambuild2/frontend/v2_1/cpp/detect.py, ambuild2/frontend/v2_1/cpp/msvc.py, ambuild2/frontend/v2_1/prep.py, ambuild2/frontend/v2_1/vs/gen.py, ambuild2/nodetypes.py, ambuild2/run.py, ambuild2/task.py, ambuild2/util.py, tests/staticlib/configure.py
This is a major refactoring of the C++ detection logic. The new behavior
is as follows:
1. If 'CC' and 'CXX' are defined in the environment, those most result
in a valid compiler, and no other detection is performed. On
Windows, tools like "rc" and "lib" must be in the environment.
Defining CC but not CXX (or vice-versa) is an error.
2. If running on Windows, if 'cl.exe' is in PATH, then AMBuild assumes
the environment has already been configured, and looks for, in this
order: cl, clang, gcc, icc.
3. If running on Windows, and 'cl.exe' is not in PATH, then AMBuild
looks in the registry for Visual Studio 2015. It will also look for
the 'vswhere' tool, and if present, will detect installations of
Visual Studio 2017 and 2019. The highest working version is used. If
no working version is …
=> Automatically detect Microsoft Visual C++.

setup.py
Note: The required plugin only supports Python 2.7+, pinned to minimum version of 1.1.5 (runtime issue/no Python 2.7 support on earlier versions)
Example output on my local machine: ```AMBuild-2.1.1.436+git.43ac8773```
Closes #82
=> Added support for auto versioning of AMBuild.

ambuild2/frontend/base_generator.py, ambuild2/frontend/v2_2/amb2_gen.py, ambuild2/frontend/v2_2/context.py, ambuild2/frontend/v2_2/cpp/builders.py, ambuild2/frontend/v2_2/cpp/compiler.py, tests/multiarch/core/AMBuild
The Projects API was designed for multi-architecture use, back when we
had to hack support for that in each build script. Now, they need to be
decoupled from compilers to properly support multi-arch builds.
This patch removes the interface for projects off the C++ compiler and
into the build context, meaning, it will go through the generator. This
will also make vsgen support of the 2.2 API a little cleaner.
=> Refactor the Projects API.

ambuild2/builder.py, ambuild2/context.py, ambuild2/task.py
When a build fails, sometimes it's really hard to see what job it
actually fails on. For example, shared C++ files make this tricky. This
will make AMBuild print the name of the output that failed to generate.
=> Improve failed build error messaging.

ambuild2/frontend/msvc_utils.py
`vswhere` encodes the output using the system's code page by default. Python tries to parse the output as utf8, so tell vswhere to output utf8 too.
=> Fix msvc detection on non-english installations

ambuild2/frontend/system.py, ambuild2/frontend/v2_2/cpp/builders.py, ambuild2/frontend/v2_2/cpp/detect.py, ambuild2/util.py
This doesn't affect x86/x86_64 which have no subarch or abi to care about. On ARMv7 however, the System object looks more complicated. For example, on an r-pi 3: `("linux", "arm", "v71", "gnueabihf")`
=> Add sub-architecture and ABI to System objects.

ambuild2/frontend/vs/gen.py
Trying to generate Visual Studio project files and selecting the target version by --vs-version=2019 failed due to recent refactorings.
=> Fix --vs-version selection by year

.gitignore, ambuild2/database.py, ambuild2/frontend/amb2_gen.py, ambuild2/frontend/v2_2/context.py, ambuild2/frontend/v2_2/cpp/builders.py, ambuild2/frontend/v2_2/cpp/gcc.py, ambuild2/frontend/v2_2/cpp/msvc.py, ambuild2/frontend/v2_2/cpp/vendor.py, ambuild2/nodetypes.py, ambuild2/task.py
Previously, the only way to do this was to add a bunch of boilerplate,
creating a command node around something like "echo", or a custom
script. Simply opening and writing an output file would not be properly
integrated into the dependency graph.
The new API, "AddOutputFile", allows build scripts to specify a file
namd and its binary contents. This creates a job in the build and
returns a node that can be used as a dependency.
=> Add a way to write files as part of the build.

ambuild2/frontend/v2_2/context.py, ambuild2/frontend/v2_2/cpp/builders.py
This was used by SourceMod to achieve special linkage rules for HL2SDK
shared libraries. Its functionality is easily replaced with Entry nodes
and weaklinkdeps.
Also, simplify AddSymlink and friends.
=> Remove the Dep API.

ambuild2/run.py
Once this is merged, the 2.2 API must retain backward compatibility.
=> Make 2.2 the default API.

ambuild2/database.py
This prevents the `Note: upgrading database from version 5 to 6` message on a clean AMBuild install.
=> Set default DB version to 6

ambuild2/frontend/v2_2/context_manager.py
The "builder" that gets exposed is a proxy object that supports magic
cloning when the builder is nested. We need to expose this proxy, not
the outer context object.
=> Fix var propagation on lambda contexts.

ambuild2/frontend/v2_2/cpp/builders.py, ambuild2/frontend/v2_2/cpp/compiler.py, ambuild2/frontend/v2_2/cpp/deptypes.py, ambuild2/frontend/v2_2/cpp/detect.py, ambuild2/frontend/v2_2/cpp/gcc.py, ambuild2/frontend/v2_2/cpp/msvc.py, ambuild2/frontend/v2_2/cpp/vendor.py, ambuild2/run.py
AMBuild makes it difficult to create both a static and dynamic library from the same object files. Initially, my thought was to make it automatic, but it's a bit difficult because a library may have multiple archives as input, and it's not easy to transitively build a new archive with the current API.
Rather than get too far into the weeds with this, we instead attach "linker" and "archiver" objects as part of DetectCxx(). There are also "linker_argv" and "archiver_argv" variables for manually invoking them.
If AMBuild can't detect both the "ld" and "ar" parts of the toolchain, configuration fails.
=> Add helpers for ld/link.exe and ar/lib.exe

.github/workflows/ci.yml, ambuild2/frontend/cpp/msvc_utils.py, ambuild2/frontend/v2_1/cpp/detect.py, ambuild2/frontend/v2_1/prep.py, ambuild2/frontend/v2_2/cpp/detect.py, ambuild2/frontend/v2_2/prep.py, ambuild2/util.py
Visual Studio 2022 17.4 (Preview 1) and previous preview versions of 17.3 added native arm64 binaries of cl.exe and other MSVC build tools. These are not currently being used by ambuild. Also note that an arm64 version of Python 3.11 is currently available as a release candidate here: https://www.python.org/downloads/release/python-3110rc1/
I have tested against these on an arm64 Windows 11 VM using the arm64, x64, and x86 versions of Python. I have also tested these changes on an x64 Windows 10 machine.
=> Use native ARM64 MSVC tools if available.

ambuild2/frontend/v2_2/vs/cxx.py, ambuild2/frontend/v2_2/vs/export_vcxproj.py, ambuild2/frontend/vs/gen.py
This adds compiler arch lookup to target correct platform arch, so the end project would be correctly generated for x64 projects. Previously it would end up generating x86 vcxproj files no matter what for a few reasons:
1. ``Compiler::clone`` function that's commonly used through out the metamod & sourcemod and other solutions (example: https://github.com/alliedmodders/metamod-source/blob/2261ff4f9c898933e02363f337de4f0dff77e687/AMBuildScript#L347 https://github.com/alliedmodders/sourcemod/blob/20aae06f127d021734ee2ff8b9664907ca7ea752/AMBuildScript#L536-L546 etc) doesn't respect the ``target.arch`` and doesn't pass it to the newly created instance which expects ``target_arch``, resulting in further code in build scripts to target x86 instead of what was asked for. Fixing this correctly …
=> Improve VS generation for x64 projects

ambuild2/frontend/v2_2/vs/cxx.py, ambuild2/frontend/v2_2/vs/export_vcxproj.py, ambuild2/frontend/vs/gen.py
Tested on metamod builds.
Resolves #143
=> Add VS2022 support, fix broken export if WindowsSDKVersion doesn't exist in environment variables

ambuild2/context.py
https://docs.python.org/3/whatsnew/3.12.html
- The asynchat, asyncore, and imp modules have been removed, along with several unittest.TestCase method aliases.
https://github.com/alliedmodders/ambuild/blob/417517c1ec86c0a1a90e1ad37faf0b8b68654fa3/ambuild2/context.py#L19
`imp` is being imported in `context.py` but not used, let's strip that ?
=> Fix AMBuild for python 3.12

ambuild2/frontend/amb2_gen.py, ambuild2/frontend/v2_2/context.py, ambuild2/frontend/v2_2/prep.py, ambuild2/frontend/v2_2/tools/__init__.py, ambuild2/frontend/v2_2/tools/protoc.py, ambuild2/frontend/v2_2/vs/export_vcxproj.py, ambuild2/make_parser.py, ambuild2/run.py
This adds a new API, and bumps the API version to 2.2.4.
DetectProtoc() returns a Protoc object. The Generate method on this is a
handy wrapper around builder.AddCommand. It returns a dictionary
mapping where generated sources and headers are. Eg,
out = protoc.Generate(sources = ['blah.proto'], outputs = ['cpp', 'py'])
Will return a map that looks like:
{
'cpp': {
'sources': Entry('blah.pb.cc'),
'headers': Entry('blah.pb.h'),
},
'python': {
'sources': Entry('blah_pb2.py'),
},
}
=> Add initial protobuf support.

.github/workflows/ci.yml, ambuild2/frontend/cpp/cpp_rules_test.py, ambuild2/frontend/v2_2/tools/protoc.py, setup.py
This also fixes a bug where protoc couldn't be invoked multiple times on the same inputs, because dependency files weren't shared outputs.
It's a little gross to use shared outputs here, but the alternative is putting every .d file in its own subdir, which is even grosser.
Usage:
cxx = builder.DetectCxx()
protoc = builder.DetectProtoc()
out = protoc.StaticLibrary('protos', builder, cxx, ['blah.proto'])
other_binary = builder.Library('mylibrary')
other_binary.compiler.sourcedeps += out.headers
other_binary.compiler.linkflags += [out.lib.binary]
...
=> Add a StaticLibrary() helper to Protoc.

ambuild2/frontend/v2_2/tools/__init__.py, ambuild2/frontend/v2_2/tools/protoc.py
Example:
prog = cxx.Program('prog')
protos = builder.tools.Protoc(sources = ['myproto.proto'])
prog.custom += [protos]
=> Add a Protoc C++ custom tool.

ambuild2/frontend/cpp/msvc_utils.py
There's no guarantee that the encoding of `subprocess.check_output` is `utf-8`, so characters like `ä` inside the environment will cause `msvc_utils.DeduceEnv` to throw an exception. The PR adds a function that finds the correct code page so the output can be decoded properly.
=> Fix check_output erroring due to incorrect encoding

ambuild2/frontend/cpp/msvc_utils.py
Python doesn't have an alias for every number, only some common one such as `437`, `850`,... `65001` is not one of them and it's used in github's windows CI environment. But in most cases, they should exist under the `cp<number>` format. The PR also makes sure that the codepage search will fall back to utf-8 if they can't find a corresponding codecs to the subprocess output.
=> Fix code page detection errors

ambuild2/frontend/v2_2/tools/protoc.py
I can see my terminal color changing to magenta after running `configure.py`.
=> Fix term color restoration in protoc.py

tests/autoinclude/AMBuildScript, tests/cx_paths/AMBuildScript, tests/cx_paths/helper/helper.ambuild, tests/cx_paths/program.ambuild
I guess these got written before the API 2.1 was finalized.
=> Fix cx_paths and autoinclude tests

ambuild2/util.py
Prevents files like aa.bb.cpp from getting clobbered
=> Do not path split in MakeLexicalFilename

ambuild2/frontend/v2_2/vs/export_vcxproj.py
`/Gm` is not compatible with later versions of VS and on the versions that still support it, the build can sometimes fail to notice changes in header files for whatever reason.
=> Disable minimal rebuild on VS exports

ambuild2/frontend/v2_2/vs/cxx.py, ambuild2/frontend/v2_2/vs/export_vcxproj.py
Fixes the below issue when using vs gen with current SourceMod code
```
Traceback (most recent call last):
File "C:\Python312\Lib\site-packages\ambuild2\frontend\v2_2\prep.py", line 156, in Configure
if not cm.generate(options.generator):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\site-packages\ambuild2\frontend\context_manager.py", line 93, in generate
self.parseBuildScripts()
File "C:\Python312\Lib\site-packages\ambuild2\frontend\v2_2\context_manager.py", line 50, in parseBuildScripts
self.execContext(cx)
File "C:\Python312\Lib\site-packages\ambuild2\frontend\v2_2\context_manager.py", line 148, in execContext
exec(code, scriptGlobals)
File "G:\sm\sourcemod\AMBuildScript", line 590, in <module>
builder.Build('public/safetyhook/AMBuilder', {'SafetyHook': SafetyHook })
File …
```
=> Make naming of name attribute consistent between vs gen and ambuild gen

ambuild2/frontend/v2_2/context_manager.py
This fixes an issue on non-Windows platforms, where passing an absolute path to builder.Eval results in broken path handling (with the absolute path being appended to the current relative path).
=> fix: Eval scripts no longer mangle absolute paths

ambuild2/frontend/cpp/msvc_utils.py
When running `chcp` on a german Windows installation, the output contains a `.` after the code page:
```
> chcp
Aktive Codepage: 850.
```
Allow an optional dot in the output parsing and fallback to utf8 if the output parsing fails.
```
Could not run or analyze C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsamd64_x86.bat: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
<unknown>:2: SyntaxWarning: invalid escape sequence '\d'
<unknown>:1: SyntaxWarning: invalid escape sequence '\d'
File "C:\Users\Jannik\AppData\Local\Programs\Python\Python313\Lib\site-packages\ambuild2\frontend\v2_2\cpp\detect.py", line 318, in try_msvc_bat
env_cmds = msvc_utils.DeduceEnv(bat_file, argv)
File …
```
=> Fix Windows codepage detection when using language pack

ambuild2/frontend/amb2_gen.py, ambuild2/frontend/v2_2/prep.py
Added an option to generate the compile_commands.json file needed for [Clangd](https://clang.llvm.org/docs/JSONCompilationDatabase.html). Makes it basically zero-click to get projects configured with an LSP.
=> Generate compile_commands.json for Clangd

ambuild2/frontend/vs/gen.py
Currently trying to generate a VS solution from a buildscripts that calls to AddOutputFile builder api would result in the following error:
```
AttributeError: 'Generator' object has no attribute 'addOutputFile'
```
coming from this location https://github.com/alliedmodders/ambuild/blob/7c2f72f0fe46a7d6137bfe64d9b43b85c3cd30f7/ambuild2/frontend/v2_2/context.py#L242-L243
This pr adds a stub ``addOutputFile`` method to VS generator which resolves the issue.
=> Fix VS generator missing addOutputFile definition
